CREATE DEFINER=`root`@`localhost` PROCEDURE `ALTA_LIBROS`(ISBN VARCHAR (15), TIT VARCHAR (40), AUT VARCHAR (40), EDITORIAL VARCHAR (40))
BEGIN

	INSERT INTO LIBROS (ISBN,TITULO,AUTOR,EDITORIAL) VALUES (ISBN,TIT,AUT,EDITORIAL);
END