CREATE DEFINER=`root`@`localhost` FUNCTION `SANCION_USUARIO`(FECHA_ENTREGA DATE) RETURNS varchar(12) CHARSET utf8mb4 COLLATE utf8mb4_general_ci
BEGIN
	DECLARE PENAL INTEGER;
    DECLARE ESTADO VARCHAR (15);
    

   SET PENAL = DATEDIFF(NOW(),FECHA_ENTREGA);
   
   
	IF (PENAL <= 7) THEN 
		SET ESTADO = 'ACTIVO';
	elseif (PENAL >7 && PENAL<12) then
		SET ESTADO = 'GRAVE';
	ELSEIF (PENAL > 12) THEN
		SET ESTADO = 'MUY GRAVE';
	ELSE 
		SET ESTADO = 'ERROR EN LOS DIAS';
	END IF;
	
    
    
RETURN ESTADO;
END