CREATE DEFINER=`root`@`localhost` PROCEDURE `GESTOR`()
BEGIN

	DECLARE CONTADOR INTEGER;
    DECLARE REGISTROS INTEGER;
    DECLARE DIAS_SANCION INTEGER;
    DECLARE SANCION VARCHAR (10);
    DECLARE CODIGO INTEGER;
    DECLARE NOMBRE_COMPL VARCHAR (30);
    DECLARE FECHAE DATE;
    DECLARE DIASPENAL INTEGER;
    DECLARE ESTADO VARCHAR (10);
    

    SET CONTADOR = 1;
    SET REGISTROS = (SELECT MAX(CODPRES) FROM PRESTAMOS);

    
    
    while (CONTADOR <= REGISTROS) DO
		
		IF EXISTS (SELECT * FROM prestamos WHERE codpres = CONTADOR) THEN 

		SELECT CODPRES, CONCAT(NOMBRE,",",APELLIDOS),FECHA_ENTREGA,NIVEL_SANCION 
		INTO CODIGO,NOMBRE_COMPL,FECHAE,ESTADO 
        FROM PRESTAMOS INNER JOIN USUARIOS 
		ON USUARIOS.COD=PRESTAMOS.CODUSU WHERE CODPRES=CONTADOR;
        
        SET ESTADO = SANCION_USUARIO(FECHAE);
		SET diasPenal = DATEDIFF(now(), FECHAE);

        
		UPDATE PRESTAMOS SET NIVEL_SANCION = SANCION_USUARIO (FECHAE) WHERE CODPRES= CONTADOR;
		UPDATE PRESTAMOS SET MENSAJE = MENSAJE_SANCION (codigo,nombre_compl,fechaE,diasPenal,estado) WHERE CODPRES= CONTADOR;
        
		
			IF (ESTADO= 'GRAVE' OR ESTADO = 'MUY GRAVE') THEN
				
				INSERT INTO SANCIONADOS (CODIGO_USUARIO, FECHA_PRESTAMO,MENSAJE)
				SELECT CODUSU, FECHA_ENTREGA, MENSAJE
				FROM PRESTAMOS WHERE CODPRES = CONTADOR
                AND NOT EXISTS (SELECT * FROM SANCIONADOS WHERE CODIGO_USUARIO = PRESTAMOS.CODUSU 
                AND FECHA_PRESTAMO = prestamos.FECHA_ENTREGA);
                
                UPDATE SANCIONADOS SET DIAS_SANCION = 60; 
			END IF;
		END IF;
            
        
		   SET CONTADOR = CONTADOR +1;
           
    END WHILE;

END