CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERTAR_PRESTAMO`( USERCODE INTEGER, LIBROCODE INTEGER)
BEGIN
	
    DECLARE FECHAENTREGA TIMESTAMP;
    DECLARE ESTADO VARCHAR (10);
    DECLARE CONTADOR INTEGER;
    DECLARE MSG VARCHAR (30);
    DECLARE REGISTROS INTEGER;
    
    SET FECHAENTREGA= NOW();
	SET ESTADO = 'ACTIVO';  /* al insertar un prestamo automaticamente lo considero como activo */
	
    

        IF  NOT EXISTS (SELECT 1 FROM SANCIONADOS WHERE CODIGO_USUARIO=USERCODE) THEN

		INSERT INTO PRESTAMOS (CODUSU,CODLIB) VALUES (USERCODE,LIBROCODE);
		UPDATE PRESTAMOS SET FECHA_DEVO_ESPERADA= date_add(fechaentrega, interval 7 day);
		UPDATE PRESTAMOS SET NIVEL_SANCION= ESTADO;
        
	END IF;
END