CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERTAR_USUARIO`(DNI VARCHAR(20), EM VARCHAR (40), NOM VARCHAR(20), APE VARCHAR(30), TL VARCHAR (15), DI VARCHAR(40))
BEGIN

	INSERT INTO USUARIOS (DNI,EMAIL,NOMBRE,APELLIDOS,TLF,DIR) values (DNI,EM,NOM,APE,TL,DI);
    
END