CREATE DATABASE ACTIVIDAD_5;
USE ACTIVIDAD_5;

CREATE TABLE USUARIOS (

	COD integer auto_increment primary key,
    DNI varchar(20) unique not null,
    email varchar (30) not null,
    nombre varchar(30) not null,
	apellidos varchar(50) not null,
    TLF varchar (15) UNIQUE not null,
    Dir varchar (40)  not null
);

CREATE TABLE LIBROS (

	COD INTEGER auto_increment primary KEY,
    ISBN VARCHAR (15) UNIQUE NOT NULL,
    TITULO VARCHAR (40) NOT NULL,
    AUTOR VARCHAR  (40) NOT NULL,
    EDITORIAL VARCHAR (40)
    
);

CREATE TABLE PRESTAMOS ( 

	CODPRES integer auto_increment primary key,
    CODUSU integer,
    CODLIB integer,
    FECHA_ENTREGA TIMESTAMP DEFAULT current_timestamp,
    FECHA_DEVO_ESPERADA DATE,
	FECHA_DEVO DATE,
    NIVEL_SANCION VARCHAR (20),
    MENSAJE MEDIUMTEXT,
	FOREIGN KEY (CODUSU) REFERENCES USUARIOS (COD)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY (CODLIB) REFERENCES LIBROS (COD)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS SANCIONADOS (
	CODIGO_USUARIO INTEGER,
	FECHA_PRESTAMO DATE,
	DIAS_SANCION INTEGER,
	MENSAJE VARCHAR(300),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
